In [1]:
import pandas as pd

## MASTER TABLE = customers (thông tin khách hàng), geography(danh sách mã bưu chính các vùng), products (sản phẩm), promotions (chiến dịch khuyến mại)

In [2]:
df_cust = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/customers.csv')
df_cust

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search
...,...,...,...,...,...,...,...
121925,157556,59936,Vung Tau,2016-03-03,Female,18-24,direct
121926,157557,59936,Vung Tau,2021-05-11,Female,45-54,social_media
121927,157558,59936,Vung Tau,2017-02-27,Female,25-34,referral
121928,157561,59937,Buon Ma Thuot,2018-10-15,Non-binary,45-54,paid_search
121929,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media

In [3]:
df_geo = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/geography.csv')
df_geo

         zip           city region      district
0      15201      Hai Phong   East  District #13
1      15202         Phu Ly   East  District #13
2      15203       Viet Tri   East  District #13
3      15204      Bac Giang   East  District #13
4      15205      Bac Giang   East  District #13
...      ...            ...    ...           ...
39943  59933         Pleiku   West  District #33
39944  59934      Soc Trang   West  District #33
39945  59935       Rach Gia   West  District #33
39946  59936       Vung Tau   West  District #33
39947  59937  Buon Ma Thuot   West  District #33

[39948 rows x 4 columns]

In [4]:
df_prod = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/products.csv')
df_prod

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406
...,...,...,...,...,...,...,...,...
2407,1260,VietMode MP-28,Casual,Activewear,S,red,4603.340000,2553.933032
2408,1261,VietMode MP-29,Casual,Activewear,M,black,5983.876433,4653.660702
2409,1262,VietMode MP-30,Casual,Activewear,L,orange,5983.876433,5684.682611
2410,1263,VietMode MP-31,Casual,Activewear,XL,blue,5984.370000,5685.151500
2411,1264,VietMode MP-32,Casual,Activewear,S,white,5984.370000,3719.884392

In [5]:
df_promotions = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/promotions.csv')
df_promotions

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,NaN,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,NaN,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,NaN,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,NaN,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000
5,PROMO-0006,Rural Special 2013,percentage,15.0,2013-01-31,2013-03-01,Outdoor,in_store,0,0
6,PROMO-0007,Spring Sale 2014,percentage,12.0,2014-03-18,2014-04-17,NaN,email,1,0
7,PROMO-0008,Mid-Year Sale 2014,percentage,18.0,2014-06-23,2014-07-22,NaN,social_media,0,0
8,PROMO-0009,Fall Launch 2014,percentage,10.0,2014-08-30,2014-10-01,NaN,all_channels,0,100000
9,PROMO-0010,Year-End Sale 2014,percentage,20.0,2014-11-19,2015-01-02,NaN,all_channels,0,100000
10,PROMO-0011,Spring Sale 2015,percentage,12.0,2015-03-18,2015-04-17,NaN,all_channels,1,100000
11,PROMO-0012,Mid-Year Sale 2015,percentage,18.0,2015-06-23,2015-07-22,NaN,social_media,0,0
12,PROMO-0013,Fall Launch 2015,percentage,10.0,2015-08-30,2015-10-01,NaN,email,1,0
13,PROMO-0014,Year-End Sale 2015,percentage,20.0,2015-11-18,2016-01-02,NaN,all_channels,1,150000
14,PROMO-0015,Urban Blowout 2015,fixed,50.0,2015-07-30,2015-09-02,Streetwear,online,0,200000
15,PROMO-0016,Rural Special 2015,percentage,15.0,2015-01-30,2015-03-01,Outdoor,in_store,0,0
16,PROMO-0017,Spring Sale 2016,percentage,12.0,2016-03-18,2016-04-17,NaN,all_channels,0,0
17,PROMO-0018,Mid-Year Sale 2016,percentage,18.0,2016-06-23,2016-07-22,NaN,online,0,0
18,PROMO-0019,Fall Launch 2016,percentage,10.0,2016-08-30,2016-10-01,NaN,online,0,0
19,PROMO-0020,Year-End Sale 2016,percentage,20.0,2016-11-18,2017-01-02,NaN,all_channels,0,0
20,PROMO-0021,Spring Sale 2017,percentage,12.0,2017-03-18,2017-04-17,NaN,all_channels,0,0
21,PROMO-0022,Mid-Year Sale 2017,percentage,18.0,2017-06-23,2017-07-22,NaN,online,0,150000
22,PROMO-0023,Fall Launch 2017,percentage,10.0,2017-08-30,2017-10-02,NaN,all_channels,1,0
23,PROMO-0024,Year-End Sale 2017,percentage,20.0,2017-11-18,2018-01-02,NaN,all_channels,0,0
24,PROMO-0025,Urban Blowout 2017,fixed,50.0,2017-07-30,2017-09-02,Streetwear,online,0,150000
25,PROMO-0026,Rural Special 2017,percentage,15.0,2017-01-30,2017-03-01,Outdoor,in_store,0,0
26,PROMO-0027,Spring Sale 2018,percentage,12.0,2018-03-18,2018-04-17,NaN,all_channels,0,100000
27,PROMO-0028,Mid-Year Sale 2018,percentage,18.0,2018-06-23,2018-07-22,NaN,social_media,0,150000
28,PROMO-0029,Fall Launch 2018,percentage,10.0,2018-08-30,2018-10-01,NaN,email,0,0
29,PROMO-0030,Year-End Sale 2018,percentage,20.0,2018-11-18,2019-01-02,NaN,all_channels,0,0
30,PROMO-0031,Spring Sale 2019,percentage,12.0,2019-03-18,2019-04-17,NaN,online,1,150000
31,PROMO-0032,Mid-Year Sale 2019,percentage,18.0,2019-06-23,2019-07-22,NaN,social_media,0,0
32,PROMO-0033,Fall Launch 2019,percentage,10.0,2019-08-30,2019-10-01,NaN,email,0,50000
33,PROMO-0034,Year-End Sale 2019,percentage,20.0,2019-11-18,2020-01-02,NaN,all_channels,0,50000
34,PROMO-0035,Urban Blowout 2019,fixed,50.0,2019-07-30,2019-09-02,Streetwear,online,0,100000
35,PROMO-0036,Rural Special 2019,percentage,15.0,2019-01-30,2019-03-01,Outdoor,in_store,1,150000
36,PROMO-0037,Spring Sale 2020,percentage,12.0,2020-03-18,2020-04-17,NaN,online,0,0
37,PROMO-0038,Mid-Year Sale 2020,percentage,18.0,2020-06-23,2020-07-22,NaN,social_media,0,0
38,PROMO-0039,Fall Launch 2020,percentage,10.0,2020-08-30,2020-10-01,NaN,all_channels,0,150000
39,PROMO-0040,Year-End Sale 2020,percentage,20.0,2020-11-18,2021-01-01,NaN,all_channels,0,0
40,PROMO-0041,Spring Sale 2021,percentage,12.0,2021-03-18,2021-04-17,NaN,online,1,0
41,PROMO-0042,Mid-Year Sale 2021,percentage,18.0,2021-06-23,2021-07-22,NaN,social_media,1,0
42,PROMO-0043,Fall Launch 2021,percentage,10.0,2021-08-30,2021-10-02,NaN,email,0,0
43,PROMO-0044,Year-End Sale 2021,percentage,20.0,2021-11-18,2022-01-02,NaN,all_channels,1,0
44,PROMO-0045,Urban Blowout 2021,fixed,50.0,2021-07-30,2021-09-02,Streetwear,online,0,200000
45,PROMO-0046,Rural Special 2021,percentage,15.0,2021-01-30,2021-03-01,Outdoor,in_store,0,0
46,PROMO-0047,Spring Sale 2022,percentage,12.0,2022-03-18,2022-04-17,NaN,all_channels,1,0
47,PROMO-0048,Mid-Year Sale 2022,percentage,18.0,2022-06-23,2022-07-22,NaN,online,0,0
48,PROMO-0049,Fall Launch 2022,percentage,10.0,2022-08-31,2022-10-01,NaN,all_channels,0,0
49,PROMO-0050,Year-End Sale 2022,percentage,20.0,2022-11-18,2022-12-31,NaN,all_channels,0,50000

# Transaction table: orders (đơn hàng), order_items (chi tiết đơn hàng), payments (thanh toán), shipments (vận chuyển), returns (trả hàng), reviews (đánh giá)

In [6]:
df_orders = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/orders.csv')
df_orders

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign
...,...,...,...,...,...,...,...,...
646940,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign
646941,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral
646942,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign
646943,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct
646944,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search

In [7]:
df_order_items = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/order_items.csv')
df_order_items

/tmp/ipykernel_56/4293495859.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_order_items = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/order_items.csv')

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2
0,1,2400,7,1138.22,0.0,NaN,NaN
1,2,609,7,10166.25,0.0,NaN,NaN
2,3,396,3,11220.33,0.0,NaN,NaN
3,4,635,5,10639.25,0.0,NaN,NaN
4,6,1935,1,1597.84,0.0,NaN,NaN
...,...,...,...,...,...,...,...
714664,834372,690,8,4473.92,0.0,NaN,NaN
714665,834377,1995,7,5250.79,0.0,NaN,NaN
714666,834387,2331,8,7389.06,0.0,NaN,NaN
714667,834392,1115,5,4767.33,0.0,NaN,NaN
714668,834397,1118,1,4716.75,0.0,NaN,NaN

In [8]:
df_payments = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/payments.csv')
df_payments

        order_id payment_method  payment_value  installments
0              1    credit_card        7967.54             3
1              2            cod       71163.75             1
2              3    credit_card       33660.99             3
3              4    credit_card       53196.25             3
4              6         paypal        1597.84             1
...          ...            ...            ...           ...
646940    834372    credit_card       35791.36             3
646941    834377    credit_card       36755.53             3
646942    834387    credit_card       59112.48             1
646943    834392         paypal       23836.65             1
646944    834397    credit_card        4716.75             3

[646945 rows x 4 columns]

In [9]:
df_shipments = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/shipments.csv')
df_shipments

        order_id   ship_date delivery_date  shipping_fee
0              1  2012-07-07    2012-07-11          1.37
1              2  2012-07-06    2012-07-10          2.60
2              3  2012-07-04    2012-07-07          2.38
3              4  2012-07-05    2012-07-11          2.49
4              6  2012-07-09    2012-07-16         25.79
...          ...         ...           ...           ...
566062    834196  2022-12-29    2022-12-31          2.22
566063    834293  2022-12-29    2022-12-31         26.83
566064    834299  2022-12-28    2022-12-31          1.23
566065    834314  2022-12-29    2022-12-31          2.28
566066    834325  2022-12-28    2022-12-30          1.09

[566067 rows x 4 columns]

In [10]:
df_returns = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/returns.csv')
df_returns

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76
...,...,...,...,...,...,...,...
39934,RET-051470,832867,653,2022-12-27,wrong_size,3,24741.62
39935,RET-051471,832890,792,2022-12-30,late_delivery,1,560.50
39936,RET-051481,833005,449,2022-12-31,defective,1,10002.55
39937,RET-051494,833234,1085,2022-12-28,wrong_size,1,815.57
39938,RET-051504,833351,2254,2022-12-30,late_delivery,3,1643.47

In [11]:
df_reviews = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/reviews.csv')
df_reviews

,review_id,order_id,product_id,customer_id,review_date,rating,review_title
0,REV-0000001,1,2400,58578,2012-07-24,5,Highly recommend
1,REV-0000002,3,396,58811,2012-08-03,5,Very satisfied
2,REV-0000003,10,1431,49101,2012-07-23,5,Great quality
3,REV-0000005,16,1668,41028,2012-08-05,5,Great quality
4,REV-0000006,17,2352,42030,2012-07-17,4,Good overall
...,...,...,...,...,...,...,...
113546,REV-0146937,833044,452,133643,2022-12-31,4,Happy with purchase
113547,REV-0146943,833081,2224,37745,2022-12-31,5,Excellent product!
113548,REV-0146946,833094,2197,62534,2022-12-27,1,Not as described
113549,REV-0146948,833108,407,17298,2022-12-30,4,Works well
113550,REV-0146984,833296,778,139570,2022-12-28,5,Excellent product!

## Analytical: sales.csv (dữ liệu doanh thu)

In [12]:
df_sales = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/sales.csv')
df_sales

            Date     Revenue        COGS
0     2012-07-04  5123547.94  3982991.19
1     2012-07-05  2751773.45  2150580.23
2     2012-07-06  3054029.42  2517632.84
3     2012-07-07  2667930.94  2108246.62
4     2012-07-08  2360851.90  1808622.79
...          ...         ...         ...
3828  2022-12-27  2100553.66  2184872.24
3829  2022-12-28  3448729.20  3513621.00
3830  2022-12-29  3083944.33  3170787.10
3831  2022-12-30  2884668.76  3022292.15
3832  2022-12-31  2383037.48  2279288.13

[3833 rows x 3 columns]

## Opeational Table: inventory.csv( tổn kho), web_traffic.csv (lưu lượng truy cập)

In [13]:
df_inventory = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/inventory.csv')
df_inventory

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,fill_rate,stockout_flag,overstock_flag,reorder_flag,sell_through_rate,product_name,category,segment,year,month
0,2022-10-31,1,3,1,1,2,90.0,0.9333,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,10
1,2022-11-30,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,11
2,2022-12-31,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,12
3,2016-04-30,3,35,13,11,2,95.5,0.9333,1,1,0,0.2391,DragonWear MA-03,Casual,All-weather,2016,4
4,2016-05-31,3,36,11,10,1,108.0,0.9667,1,1,0,0.2174,DragonWear MA-03,Casual,All-weather,2016,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60242,2022-08-31,2412,251,25,21,2,358.6,0.9333,1,1,0,0.0772,VietMotion YY-21,GenZ,Trendy,2022,8
60243,2022-09-30,2412,251,3,3,2,2510.0,0.9333,1,1,0,0.0118,VietMotion YY-21,GenZ,Trendy,2022,9
60244,2022-10-31,2412,251,3,3,0,2510.0,1.0000,0,1,0,0.0118,VietMotion YY-21,GenZ,Trendy,2022,10
60245,2022-11-30,2412,251,3,3,0,2510.0,1.0000,0,1,0,0.0118,VietMotion YY-21,GenZ,Trendy,2022,11
60246,2022-12-31,2412,253,17,15,1,506.0,0.9667,1,1,0,0.0560,VietMotion YY-21,GenZ,Trendy,2022,12

In [14]:
df_web_traffic = pd.read_csv('/kaggle/input/competitions/datathon-2026-round-1/web_traffic.csv')
df_web_traffic

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral
...,...,...,...,...,...,...,...
3647,2022-12-27,17416,13150,62527,0.00506,252.4,organic_search
3648,2022-12-28,21071,15979,67456,0.00560,177.3,organic_search
3649,2022-12-29,20884,14640,82155,0.00522,165.6,direct
3650,2022-12-30,17679,13713,79308,0.00350,183.8,email_campaign
3651,2022-12-31,21743,15512,94844,0.00394,151.7,organic_search

### Answer the MCQs via dataset

### Q1. Trong số các khách hàng có nhiều hơn 1 đơn hàng (orders), trung vi số ngày giữa 2 lần mua liên tiếp (inter-order gap) xấp xỉ là bao nhiêu

- Phân tích: các bảng cần phân tích: df_orders.
- Cột cần quan tâm: df_orders.customer_id, df_orders.order_date

In [15]:
import pandas as pd

# 1. Lấy các cột cần thiết
orders = df_orders[['customer_id', 'order_date']].copy()

# 2. Chuyển order_date sang datetime
orders['order_date'] = pd.to_datetime(orders['order_date'])

# 3. Sắp xếp theo khách hàng và ngày mua
orders = orders.sort_values(['customer_id', 'order_date'])

# 4. Đếm số đơn của từng khách
customer_order_counts = orders.groupby('customer_id').size()

# 5. Chỉ giữ khách có từ 2 đơn trở lên
multi_order_customers = customer_order_counts[customer_order_counts >= 2].index
orders = orders[orders['customer_id'].isin(multi_order_customers)].copy()

# 6. Lấy ngày mua trước đó của từng khách
orders['prev_order_date'] = orders.groupby('customer_id')['order_date'].shift(1)

# 7. Tính khoảng cách giữa 2 lần mua liên tiếp (đơn vị: ngày)
orders['inter_order_gap_days'] = (
    orders['order_date'] - orders['prev_order_date']
).dt.days

# 8. Chỉ giữ các dòng có gap hợp lệ
gaps = orders.dropna(subset=['inter_order_gap_days']).copy()

# 9. Tính trung vị
median_gap = gaps['inter_order_gap_days'].median()

# 10. Hiển thị kết quả
print(f"Median inter-order gap: {median_gap:.2f} days")

print("\nSample gaps:")
print(
    gaps[['customer_id', 'prev_order_date', 'order_date', 'inter_order_gap_days']]
    .head(10)
)

print("\nSố khách có từ 2 đơn trở lên:", len(multi_order_customers))
print("Số khoảng cách mua hàng hợp lệ:", len(gaps))

Median inter-order gap: 144.00 days

Sample gaps:
        customer_id prev_order_date order_date  inter_order_gap_days
143252            1      2012-07-25 2014-05-31                 675.0
238890            1      2014-05-31 2015-07-31                 426.0
374571            1      2015-07-31 2017-04-23                 632.0
544446            1      2017-04-23 2020-02-24                1037.0
586950            1      2020-02-24 2021-04-24                 425.0
97364             2      2013-09-20 2013-10-28                  38.0
179458            2      2013-10-28 2014-11-13                 381.0
632148            2      2014-11-13 2022-07-06                2792.0
24017             3      2012-08-27 2012-11-24                  89.0
79458             3      2012-11-24 2013-07-29                 247.0

Số khách có từ 2 đơn trở lên: 67888
Số khoảng cách mua hàng hợp lệ: 556699

## Q2. Phân khúc sản phẩm (segment) nào trong products.csv có tỷ suất lợi nhuận gộp trung bình cao nhất, với công thức (price −cogs)/price?
- Phân tích: bảng cần phân tích: df_prod
- Cột cần phân tích df_prod.segment, df_prod.price, df_prod.cogs

In [16]:
import pandas as pd

def avg_ratio_by_segment(df_prod: pd.DataFrame) -> pd.DataFrame:
    prods = df_prod[['segment', 'price', 'cogs']].copy()

    prods = prods.dropna(subset=['segment', 'price', 'cogs'])
    prods = prods[prods['price'] != 0].copy()

    prods['ratio'] = (prods['price'] - prods['cogs']) / prods['price']

    result = (
        prods.groupby('segment', as_index=False)['ratio']
        .mean()
        .sort_values('ratio', ascending=False)
    )

    return result


result = avg_ratio_by_segment(df_prod)
print(result)

       segment     ratio
6     Standard  0.313442
5      Premium  0.285377
1  All-weather  0.284176
0   Activewear  0.265600
4  Performance  0.263650
2     Balanced  0.258038
7       Trendy  0.240758
3     Everyday  0.236343

## Q3. Trong các bản ghi trả hàng liên kết với sản phẩm thuộc danh mục Streetwear (join returns với products theo product_id), lý do trả hàng nào xuất hiện nhiều nhất?

- Bảng sử dụng: df_returns , df_prod
- Cột cần quan tâm df_prod.product_id, df_prod.category, df_returns.return_reason

In [17]:
prods_with_category = df_prod[['product_id', 'category']].copy()
prods_with_category
prod_ids_with_streetwear = prods_with_category[prods_with_category['category'] == 'Streetwear']['product_id'].to_list()
prod_ids_with_streetwear
returns_streetwear = df_returns[df_returns['product_id'].isin(prod_ids_with_streetwear)].copy()
return_reason_counts = (
    returns_streetwear['return_reason']
    .value_counts(dropna=False)
    .reset_index()
)

return_reason_counts.columns = ['return_reason', 'count']
print(return_reason_counts)

print("\nMost common return_reason:")
print(return_reason_counts.iloc[0])
# filter the df_returns that has product_id in prod_ids_with_streetwear

      return_reason  count
0        wrong_size   7626
1         defective   4330
2  not_as_described   3854
3      changed_mind   3830
4     late_delivery   2159

Most common return_reason:
return_reason    wrong_size
count                  7626
Name: 0, dtype: object

##  Q4. Trong web_traffic.csv, nguồn truy cập (traffic_source) nào có tỷ lệ thoát trung bình (bounce_rate) thấp nhất trên tất cả các ngày xuất hiện nguồn đó trong cột traffic_source?
- Bảng sử dụng: df_web_traffic
- cột quan tâm: df_web_traffic.bound_rate, df_web_traffic.traffic_source

In [18]:
web_bounce_rate = df_web_traffic[['bounce_rate', 'traffic_source']].copy()
result = (
    web_bounce_rate.groupby('traffic_source', as_index=False)['bounce_rate']
    .mean()
    .sort_values('bounce_rate', ascending=True)
)

print(result)
print("\nTraffic source có bounce_rate trung bình thấp nhất:")
print(result.iloc[0])

   traffic_source  bounce_rate
1  email_campaign     0.004458
5    social_media     0.004476
3     paid_search     0.004478
4        referral     0.004499
2  organic_search     0.004504
0          direct     0.004511

Traffic source có bounce_rate trung bình thấp nhất:
traffic_source    email_campaign
bounce_rate             0.004458
Name: 1, dtype: object

## Q5. Tỷ lệ phần trăm các dòng trong order_items.csv có áp dụng khuyến mãi (tức là promo_id không null) xấp xỉ là bao nhiêu?

In [19]:
ratio = 1 - (df_order_items['promo_id'].isna().sum() / len(df_order_items))
ratio

np.float64(0.3866349316956521)

## Q6. Trong customers.csv, xét các khách hàng có age_group khác null, nhóm tuổi nào có số đơn hàng trung bình trên mỗi khách hàng cao nhất? (tổng số đơn / số khách hàng trong nhóm)

- Bảng cần quan tâm: df_cust, df_orders
- Cột cần quan tâm: df_cust.age_group

In [20]:
import pandas as pd

# 1. Chỉ giữ khách có age_group khác null
cust = df_cust[['customer_id', 'age_group']].copy()
cust = cust[cust['age_group'].notna()].copy()

# 2. Lấy cột customer_id từ orders
orders = df_orders[['customer_id', 'order_id']].copy()

# 3. Đếm số đơn theo từng khách
orders_per_customer = (
    orders.groupby('customer_id')['order_id']
    .count()
    .reset_index(name='total_orders')
)

# 4. Ghép với bảng khách hàng
cust_orders = cust.merge(orders_per_customer, on='customer_id', how='left')

# 5. Khách không có đơn thì gán 0
cust_orders['total_orders'] = cust_orders['total_orders'].fillna(0)

# 6. Tính theo từng nhóm tuổi
age_group_stats = (
    cust_orders.groupby('age_group')
    .agg(
        total_orders=('total_orders', 'sum'),
        total_customers=('customer_id', 'nunique')
    )
    .reset_index()
)

print(age_group_stats)
age_group_stats['avg_orders_per_customer'] = (
    age_group_stats['total_orders'] / age_group_stats['total_customers']
)

# 7. Sắp xếp giảm dần để lấy nhóm cao nhất
age_group_stats = age_group_stats.sort_values(
    'avg_orders_per_customer', ascending=False
)

print(age_group_stats)

# 8. Nhóm tuổi cao nhất
top_group = age_group_stats.iloc[0]

print("\nNhóm tuổi có số đơn hàng trung bình trên mỗi khách hàng cao nhất:")
print(f"age_group: {top_group['age_group']}")
print(f"avg_orders_per_customer: {top_group['avg_orders_per_customer']:.2f}")

  age_group  total_orders  total_customers
0     18-24       89057.0            17039
1     25-34      190622.0            36342
2     35-44      170368.0            31920
3     45-54      124138.0            23172
4       55+       72760.0            13457
  age_group  total_orders  total_customers  avg_orders_per_customer
4       55+       72760.0            13457                 5.406851
3     45-54      124138.0            23172                 5.357241
2     35-44      170368.0            31920                 5.337343
1     25-34      190622.0            36342                 5.245226
0     18-24       89057.0            17039                 5.226656

Nhóm tuổi có số đơn hàng trung bình trên mỗi khách hàng cao nhất:
age_group: 55+
avg_orders_per_customer: 5.41

##  Q7. Vùng (region) nào trong geography.csv tạo ra tổng doanh thu cao nhất trong sales_train.csv

In [21]:
import pandas as pd

# 1. Các bảng cần thiết
orders = df_orders[['order_id', 'zip']].copy()
payments = df_payments[['order_id', 'payment_value']].copy()
geo = df_geo[['zip', 'region']].copy()

# 2. Tổng tiền refund theo order
refunds = (
    df_returns.groupby('order_id', as_index=False)['refund_amount']
    .sum()
    .rename(columns={'refund_amount': 'total_refund'})
)

# 3. Gộp payment với refund
df = payments.merge(refunds, on='order_id', how='left')
df['total_refund'] = df['total_refund'].fillna(0)

# 4. Tính doanh thu thuần
df['net_revenue'] = df['payment_value'] - df['total_refund']

# 5. Gắn zip và region
df = df.merge(orders, on='order_id', how='left')
df = df.merge(geo, on='zip', how='left')

# 6. Tổng doanh thu thuần theo vùng
region_revenue = (
    df.groupby('region', as_index=False)['net_revenue']
    .sum()
    .sort_values('net_revenue', ascending=False)
)

print(region_revenue)

top_region = region_revenue.iloc[0]
print("\nVùng có doanh thu thuần cao nhất:")
print(f"Region: {top_region['region']}")
print(f"Net revenue: {top_region['net_revenue']:.2f}")

    region   net_revenue
1     East  7.055669e+09
0  Central  4.568104e+09
2     West  3.546498e+09

Vùng có doanh thu thuần cao nhất:
Region: East
Net revenue: 7055669071.14

## Q8.  Trong các đơn hàng có order_status = ’cancelled’ trong orders.csv, phương thức thanh toán nào được sử dụng nhiều nhất?

In [22]:
orders = df_orders[['order_id', 'order_status', 'payment_method']].copy()
orders_be_cancelled = orders[orders['order_status'] == 'cancelled']
orders_be_cancelled
orders_be_cancelled['payment_method'].describe()

count           59462
unique              5
top       credit_card
freq            28452
Name: payment_method, dtype: object

## Q9. Trong bốn kích thước sản phẩm (S, M, L, XL), kích thước nào có tỷ lệ trả hàng cao nhất, được định nghĩa là số bản ghi trong returns chia cho số dòng trong order_items (join với products theo product_id)?

In [23]:
import pandas as pd

# 1. Lấy product_id và size
products = df_prod[['product_id', 'size']].copy()

# 2. Join order_items với products để gắn size
order_items_with_size = df_order_items.merge(
    products,
    on='product_id',
    how='left'
)

# 3. Join returns với products để gắn size
returns_with_size = df_returns.merge(
    products,
    on='product_id',
    how='left'
)

# 4. Đếm số dòng order_items theo size
order_item_counts = (
    order_items_with_size.groupby('size')
    .size()
    .reset_index(name='order_item_count')
)

# 5. Đếm số bản ghi returns theo size
return_counts = (
    returns_with_size.groupby('size')
    .size()
    .reset_index(name='return_count')
)

# 6. Gộp 2 bảng lại
size_return_rate = order_item_counts.merge(
    return_counts,
    on='size',
    how='left'
)

# 7. Size nào không có return thì gán 0
size_return_rate['return_count'] = size_return_rate['return_count'].fillna(0)

# 8. Tính tỷ lệ trả hàng
size_return_rate['return_rate'] = (
    size_return_rate['return_count'] / size_return_rate['order_item_count']
)

# 9. Sắp xếp giảm dần
size_return_rate = size_return_rate.sort_values(
    'return_rate',
    ascending=False
).reset_index(drop=True)

print(size_return_rate)

# 10. Lấy size có tỷ lệ trả hàng cao nhất
top_size = size_return_rate.iloc[0]

print("\nKích thước có tỷ lệ trả hàng cao nhất:")
print(f"Size: {top_size['size']}")
print(f"Return rate: {top_size['return_rate']:.4f}")
print(f"Return count: {int(top_size['return_count'])}")
print(f"Order item count: {int(top_size['order_item_count'])}")

  size  order_item_count  return_count  return_rate
0    S            172042          9723     0.056515
1    L            173174          9741     0.056250
2    M            176428          9820     0.055660
3   XL            193025         10655     0.055200

Kích thước có tỷ lệ trả hàng cao nhất:
Size: S
Return rate: 0.0565
Return count: 9723
Order item count: 172042

## Q10. Trong payments.csv, kế hoạch trả góp nào có giá trị thanh toán trung bình trên mỗi đơn hàng cao nhất?

In [24]:
import pandas as pd

# 1. Lấy 2 cột installments và payment_value
payments = df_payments[['installments', 'payment_value']].copy()

# 2. Tính giá trị thanh toán trung bình theo từng kế hoạch trả góp
installment_stats = (
    payments.groupby('installments', as_index=False)
    .agg(avg_payment_value=('payment_value', 'mean'))
)

# 3. Sắp xếp giảm dần để thống kê và tìm nhóm cao nhất
installment_stats = installment_stats.sort_values(
    'avg_payment_value', ascending=False
).reset_index(drop=True)

print(installment_stats)

# Lấy kế hoạch trả góp có avg cao nhất
top_plan = installment_stats.iloc[0]

print("\nKế hoạch trả góp có giá trị thanh toán trung bình cao nhất:")
print(f"Installments: {int(top_plan['installments'])}")
print(f"Average payment value: {top_plan['avg_payment_value']:.2f}")

   installments  avg_payment_value
0             6       24446.654403
1             3       24399.635486
2            12       24245.772694
3             1       24113.274166
4             2         708.473729

Kế hoạch trả góp có giá trị thanh toán trung bình cao nhất:
Installments: 6
Average payment value: 24446.65